# Generated by Django 4.1 on 2022-08-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_events'),
    ]

    operations = [
        migrations.RemoveField(model_name='events', name='id',),
        migrations.RemoveField(model_name='installs1', name='id',),
        migrations.AlterField(
            model_name='events',
            name='event_time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='events', name='install_time', field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='installs1',
            name='event_time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='installs1', name='install_time', field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(name='events', table='events',),
        migrations.AlterModelTable(name='installs1', table='installs1',),
    ]
