# Generated by Django 4.1 on 2022-08-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_events_id_remove_installs1_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(model_name='user', name='birthday',),
        migrations.AlterField(
            model_name='events',
            name='event_revenue',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_revenue_usd',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30),
        ),
    ]
